survey_managment/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'survey_managment'


urlpatterns = [
    path('',views.indexView, name='Index'),
    path('surveyCreation/',views.surveyCreationView, name='SurveyCreation'),
    path('change_password/', views.change_password,name='change_password'),
    path('forgotPassword/', views.forgotPasswordView,name='forgotPassword'),
    # path('login/', views.loginView, name='login'),

    path('compareData/', views.compareDataView, name='compareData'),
    path('questionCreationByType/<int:section_id>/', views.questionCreationByType, name='questionCreationByType'),
     path('sections/<int:survey_id>/', views.sections, name='sections'),
    path('sectionCreation/<int:survey_id>/', views.sectionCreation, name='sectionCreation'),
    path('newQuestion/<str:questionType>/<int:s_id>/', views.newQuestion, name='newQuestion'),
    # path('newCategory/', views.newCategory, name='newCategory'),
    path('createQuestion/<int:survey_id>/', views.createQuestion, name='createQuestion'),
    path('save_category/' , views.save_category, name='save_category'),

    path('survey/', views.survey, name='survey'),
    path('inbox/', views.inbox, name='inbox'),
    path('inbox/<int:message_id>/reply/', views.reply_to_message, name='reply_to_message'),
    path('sent/', views.sent, name='sent'),
    path('draft/', views.draft, name='draft'),
    path('trash/', views.trash, name='trash'),
    path('compose/', views.compose, name='compose'),
    path('read/<int:id>', views.read, name='read'),
    
    path('chooseSurvey/<int:id>/<int:choose_id>/', views.chooseSurvey, name='chooseSurvey'),
    path('displayQuestion/<int:id>/', views.displayQuestion, name='displayQuestion'),
    path('catagorizedQuestion/<int:id>/', views.catagorizedQuestion, name='catagorizedQuestion'),
    path('choose-target/<int:survey_id>/<int:question_id>/', views.chooseTarget, name='chooseTarget'),
    path('questionCreationByType/<int:survey_id>/', views.questionCreationByType, name='questionCreationByType'),
    path('QuestionCategories/', views.QuestionCategories, name='QuestionCategories'),
    path('survey/', views.survey, name='survey'),
    path('line_ministrys/', views.line_ministrys, name='line_ministrys'),
    path('line_ministrys/<int:id>', views.line_ministry_detail, name='line_ministry_detail'),
    path("pending_response/",views.pending_response,name ='pending_response'),
    path('survey_detail/<int:id>/<int:assesment_id>', views.survey_detail, name='survey_detail'),
    path('user_response_list/<int:id>', views.user_response_list, name='user_response_list'),
    path('user_response/<int:id>/<int:response_id>', views.user_response, name='user_response'),
    # path('chooseSurvey/<int:id>/<int:choose_id>/', views.chooseSurvey, name='chooseSurvey'),
    path('displayQuestion/<int:survey_id>/', views.displayQuestion, name='displayQuestion'),
    path('jsonSender/' , views.jsonSender , name = 'jsonSender'),
    # path('choose-target/<int:survey_id>/<int:question_id>/', views.chooseTarget, name='chooseTarget'),
    path('get_json/',views.get_data,name='get_data'),
    path('filter_data/',views.filter,name='filter'),
    path('years/',views.YearDataview,name="years"),
    path('years2/',views.YearDataview2,name="years2"),
    # path('choose-target/<int:survey_id>/<int:question_id>/', views.chooseTarget, name='chooseTarget'),   
    path('greetingpage/',views.greetingpage_view, name='greetingpage'),
    path('surveylists/',views.survey_listss_views, name='surveylists'),
    path('section_list/<int:survey_id>/',views.section_list, name='section_list'),
    path('section_list_anonymous/<int:survey_id>/<int:user_response_id>',views.section_list_anonymous, name='section_list_anonymous'),
    path('user_info/',views.user_info, name='user_info'),
    path('surveylistsAnonymous/<int:user_response_id>',views.anonymous_survey_listss_views, name='anonymous_survey_listss_views'),
    path('questionForSurvey/<int:id>/<int:assesment_id>' , views.questionForSurvey , name = 'questionForSurvey'),
    path('questionForSurveyAnonymous/<int:id>/<int:user_response_id>' , views.questionForSurveyAnonymous , name = 'questionForSurveyAnonymous'),
    path('recomended_survey_list/<int:survey_id>' , views.recomended_survey_list , name = 'recomended_survey_list'),
    path('recomended_survey/<int:id>' , views.recomended_survey , name = 'recomended_survey'),
    path('previous_analysis/' , views.previous_analysis , name = 'previous_analysis'),
    path("load_survey/",views.load_survey,name ='load_survey'),
    path("load_ministry/",views.load_ministry,name ='load_ministry'),
    path("assessment_category/", views.AssesmentCatagory, name='assessment_category'),
    path("LineMinistryFilter/", views.LineMinistryFilter, name='LineMinistryFilter'),




]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/includes/dashbordNav.html
{% include "includes/head.html" %}


<ul class="nav nav-tabs" style="margin: 10px; justify-content: center;">
    <li class="nav-item">
        <a class="nav-link" style="color:grey" aria-current="page" href="{% url 'survey_managment:Index'%}"
            style="background-color: transparent;" id="dashboard-link">Dashboard</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" style="color:grey" aria-current="page" href="{% url 'survey_managment:years'%}"
            style="background-color: transparent;" id="filter-detail-link">Filter Detail</a>
    </li>
</ul>

<script>
    // Get the current URL
    var currentURL = window.location.href;
    console.log(currentURL)

    // Get the link elements
    var dashboardLink = document.getElementById("dashboard-link");
    var filterLineLink = document.getElementById("filter-line-link");
    var filterDetailLink = document.getElementById("filter-detail-link");

    // Check if the current URL matches the link href and add the 'active' class
    if (currentURL"/") {
        dashboardLink.classList.add("active");
    } else if (currentURL.includes("/years2")) {
        filterLineLink.classList.add("active");
    } else if (currentURL.includes("/years")) {
        filterDetailLink.classList.add("active");
    }
</script>

templates/includes/greetingSurveyNav.html
{% load static %}
{% include "includes/style.html" %}
<div class="card-header p-2">
  <hr>
    <ul class="nav nav-pills topLinks">
        <li><a class="nav-link scrollto" href="{% url 'survey_managment:section_list' survey_id=survey_id %}" style="color: rgb(9, 109, 9);">New Sections</a></li>
        <li><a class="nav-link scrollto" href="{% url 'survey_managment:recomended_survey_list' survey_id=survey_id %}" style="color: rgb(9, 109, 9);">Recomended Sections</a></li>
    </ul>
</div>

templates/includes/topNavbar.html
{% load static %} {% include "includes/head.html" %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<nav class="main-header navbar navbar-expand" style="background-color: #f0f8ff">
  
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"
        ><i class="fas fa-bars"></i
      ></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="{% url 'survey_managment:Index' %}" class="nav-link">Home</a>
    </li>
  </ul>

  <ul class="navbar-nav ml-auto">

    <li class="nav-item">
      <a class="nav-link" data-widget="navbar-search" href="#" role="button">
        <i class="fas fa-search"></i>
      </a>
      <div class="navbar-search-block">
        <form class="form-inline">
          <div class="input-group input-group-sm">
            <input
              class="form-control form-control-navbar"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <div class="input-group-append">
              <button class="btn btn-navbar" type="submit">
                <i class="fas fa-search"></i>
              </button>
              <button
                class="btn btn-navbar"
                type="button"
                data-widget="navbar-search"
              >
                <i class="fas fa-times"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-comments"></i> <!-- Icon for the navigation link -->
        <span class="badge badge-danger navbar-badge" style="position: absolute; top: -1px; right: 0;">{{ unread_count }}</span> <!-- Badge for the unread count -->
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          {% for unread in unread %}
          <a href="#" class="dropdown-item">
            <div class="media">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  {{unread.name}}
                  <span class="float-right text-sm text-danger"
                    ><i class="fas fa-star"></i
                  ></span>
                </h3>
                <p class="text-sm">{{unread.subject}}</p>
                <p class="text-sm text-muted">
                  <i class="far fa-clock mr-1"></i>
                    {{ unread.sent_at }}
                </p>
                </p>
              </div>
            </div>
          </a>
          <div class="dropdown-divider"></div> 
          {% endfor %}  
        <a href="{% url "survey_managment:inbox" %}" class="dropdown-item dropdown-footer">See All Messages</a>
      </div>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown"  href="" >
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge ml-2" style="position: absolute; top: -1px; right: 0;">{{pending_responses}}</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header">Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="{% url "survey_managment:pending_response" %}" class="dropdown-item">
          <span>
            <i class="fas fa-spinner mr-2"></i> {{ pending_responses }} Unaproved
            responses
          </span>
        </a>
      </div>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="fa-regular fa-user"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <div class="dropdown-divider"></div>
        <a href="{%url 'Account:view_profile'%}" class="dropdown-item">
          View Profile
        </a>
        <div class="dropdown-divider"></div>
        <a href="{%url 'Account:edit_profile'%}" class="dropdown-item">
          Edit profile
        </a>
        <div class="dropdown-divider"></div>
        <a href="{%url 'Account:change_password'%}" class="dropdown-item">
          Change Password
        </a>
        <div class="dropdown-divider"></div>
        <a href="{%url 'Account:logout'%}" class="dropdown-item"> Logout </a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="fullscreen" href="#" role="button">
        <i class="fas fa-expand-arrows-alt"></i>
      </a>
    </li>
    <li class="nav-item">
      <a
        class="nav-link"
        data-widget="control-sidebar"
        data-slide="true"
        href="#"
        role="button"
      >
        <i class="fas fa-th-large"></i>
      </a>
    </li>
    <li class="nav-item">
      <a
        class="nav-link"
        href="{% url "survey_managment:greetingpage" %}"

      >
        Go To Site
      </a>
    </li>

  </ul>
</nav>