survey_managment/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'survey_managment'


urlpatterns = [
    path('',views.indexView, name='Index'),
    path('surveyCreation/',views.surveyCreationView, name='SurveyCreation'),
    path('change_password/', views.change_password,name='change_password'),
    path('forgotPassword/', views.forgotPasswordView,name='forgotPassword'),
    # path('login/', views.loginView, name='login'),

    path('compareData/', views.compareDataView, name='compareData'),
    path('questionCreationByType/<int:section_id>/', views.questionCreationByType, name='questionCreationByType'),
     path('sections/<int:survey_id>/', views.sections, name='sections'),
    path('sectionCreation/<int:survey_id>/', views.sectionCreation, name='sectionCreation'),
    path('newQuestion/<str:questionType>/<int:s_id>/', views.newQuestion, name='newQuestion'),
    # path('newCategory/', views.newCategory, name='newCategory'),
    path('createQuestion/<int:survey_id>/', views.createQuestion, name='createQuestion'),
    path('save_category/' , views.save_category, name='save_category'),

    path('survey/', views.survey, name='survey'),
    path('inbox/', views.inbox, name='inbox'),
    path('inbox/<int:message_id>/reply/', views.reply_to_message, name='reply_to_message'),
    path('sent/', views.sent, name='sent'),
    path('draft/', views.draft, name='draft'),
    path('trash/', views.trash, name='trash'),
    path('compose/', views.compose, name='compose'),
    path('read/<int:id>', views.read, name='read'),
    
    path('chooseSurvey/<int:id>/<int:choose_id>/', views.chooseSurvey, name='chooseSurvey'),
    path('displayQuestion/<int:id>/', views.displayQuestion, name='displayQuestion'),
    path('catagorizedQuestion/<int:id>/', views.catagorizedQuestion, name='catagorizedQuestion'),
    path('choose-target/<int:survey_id>/<int:question_id>/', views.chooseTarget, name='chooseTarget'),
    path('questionCreationByType/<int:survey_id>/', views.questionCreationByType, name='questionCreationByType'),
    path('QuestionCategories/', views.QuestionCategories, name='QuestionCategories'),
    path('survey/', views.survey, name='survey'),
    path('line_ministrys/', views.line_ministrys, name='line_ministrys'),
    path('line_ministrys/<int:id>', views.line_ministry_detail, name='line_ministry_detail'),
    path("pending_response/",views.pending_response,name ='pending_response'),
    path('survey_detail/<int:id>/<int:assesment_id>', views.survey_detail, name='survey_detail'),
    path('user_response_list/<int:id>', views.user_response_list, name='user_response_list'),
    path('user_response/<int:id>/<int:response_id>', views.user_response, name='user_response'),
    # path('chooseSurvey/<int:id>/<int:choose_id>/', views.chooseSurvey, name='chooseSurvey'),
    path('displayQuestion/<int:survey_id>/', views.displayQuestion, name='displayQuestion'),
    path('jsonSender/' , views.jsonSender , name = 'jsonSender'),
    # path('choose-target/<int:survey_id>/<int:question_id>/', views.chooseTarget, name='chooseTarget'),
    path('get_json/',views.get_data,name='get_data'),
    path('filter_data/',views.filter,name='filter'),
    path('years/',views.YearDataview,name="years"),
    path('years2/',views.YearDataview2,name="years2"),
    # path('choose-target/<int:survey_id>/<int:question_id>/', views.chooseTarget, name='chooseTarget'),   
    path('greetingpage/',views.greetingpage_view, name='greetingpage'),
    path('surveylists/',views.survey_listss_views, name='surveylists'),
    path('section_list/<int:survey_id>/',views.section_list, name='section_list'),
    path('section_list_anonymous/<int:survey_id>/<int:user_response_id>',views.section_list_anonymous, name='section_list_anonymous'),
    path('user_info/',views.user_info, name='user_info'),
    path('surveylistsAnonymous/<int:user_response_id>',views.anonymous_survey_listss_views, name='anonymous_survey_listss_views'),
    path('questionForSurvey/<int:id>/<int:assesment_id>' , views.questionForSurvey , name = 'questionForSurvey'),
    path('questionForSurveyAnonymous/<int:id>/<int:user_response_id>' , views.questionForSurveyAnonymous , name = 'questionForSurveyAnonymous'),
    path('recomended_survey_list/<int:survey_id>' , views.recomended_survey_list , name = 'recomended_survey_list'),
    path('recomended_survey/<int:id>' , views.recomended_survey , name = 'recomended_survey'),
    path('previous_analysis/' , views.previous_analysis , name = 'previous_analysis'),
    path("load_survey/",views.load_survey,name ='load_survey'),
    path("load_ministry/",views.load_ministry,name ='load_ministry'),
    path("assessment_category/", views.AssesmentCatagory, name='assessment_category'),
    path("LineMinistryFilter/", views.LineMinistryFilter, name='LineMinistryFilter'),




]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/Final_Preview_Pages/SL.html
{% load static %}
{% include "includes/head.html" %}
<!DOCTYPE html>
<html lang="en">
      
{% include "includes/greetingHead.html" %}
    <style>
      .progress-bar-container {
  width: 100%;
  background-color: #f2f2f2;
  border-radius: 5px;
  margin: 10px 0;
  overflow: hidden;
}

.progress-bar {
  background-color:  rgb(9, 109, 9); /* Change the color as per your design */
  height: 15px;
  line-height: 15px;
  text-align: center;
  color: #fff; /* Change the text color for better visibility */
}
      .ft p {
        font-size: x-small;
        font-weight: 400;
      }
      .card {
        box-shadow: 0 20px 27px 0 rgb(0 0 0 / 5%);
      }

      .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 0 solid rgba(0, 0, 0, 0.125);
        border-radius: 1rem;
      }

      .card-body {
        -webkit-box-flex: 1;
        -ms-flex: 1 1 auto;
        flex: 1 1 auto;
        padding: 1.5rem 1.5rem;
      }
      .avatar-text {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        background: #000;
        color: #fff;
        font-weight: 700;
      }

      .avatar {
        width: 3rem;
        height: 3rem;
      }
      .rounded-3 {
        border-radius: 0.5rem !important;
      }
      .mb-2 {
        margin-bottom: 0.5rem !important;
      }
      .me-4 {
        margin-right: 1.5rem !important;
      }
    </style>

  <body>
    <!-- ======= Header ======= -->
    
    <section id="hero" class="hero align-items-center">
    <header id="header" class="header">
      <div
        class="container-fluid container-xl d-flex align-items-center justify-content-between " style="margin-top:-50px"
      >
        <a href="#" class="logo d-flex align-items-center">
          <img src="{% static 'assets/img/logo.png' %}" alt="" />
          <span style="color: rgb(9, 109, 9)">MOPD</span>
        </a>

        {% include "includes/navBar.html" %}
       
        <!-- .navbar -->
      </div>
    </header>
    <!-- End Header -->

    <!-- ======= Hero Section ======= -->
     
    <div class="container">

     
      <div class="text-center">
        <h3 class="mb-5"  style="font-size: 40px;color:rgb(9, 109, 9);font-weight: bold;">Survey Lists</h3>
        <hr>
      </div>


      <div class="row">

       {% if surveys %}
      
            {% for survey in surveys  %}
            <div class="col-md-3 col-sm-6 col-lg-5 p-1">
             
              <div class="info-box shadow">
                
                
                  <span class="info-box-icon" style="color: rgb(9, 109, 9);">
                      <i class="far fa-copy"></i>
                  </span>                   
                  <div class="info-box-content">
                      <a href="{% url 'survey_managment:section_list' survey_id=survey.id  %}" style="color: black;text-decoration:none;">
                          <span class="info-box-text">{{ survey.name }}</span>
                          <span class="info-box-number">{{  survey.created }}</span>
                          <span class="info-box-number">{{ survey.section }} Sections </span>
                          <div class="progress-bar-container">
                            <div class="progress-bar" style="width: {{ survey.percent|floatformat:2 }}%;">
                            </div>
                        </div>
                        <span style="color:rgb(9, 109, 9);"> 
                          {{ survey.percent|floatformat:2 }}
                          % Completed
                           </span>
                      </a>
                  </div>
              </div>
          </div>
         
            {% endfor %}

            {% else %}
            <div class="container-fluid" style="display: flex; align-items: center;">
              <p style="margin: auto; color: darkgray;">No surveys found. Your Survey  will occure here.</p>
            </div>

            {% endif %}

          </div>

    </div>
    </section>
    <!-- End Hero -->
    <!-- ======= Services Section ======= -->

  
    {% include "includes/previewFooter.html" %}
    <!-- End Footer -->

    <a
      href="#"
      class="back-to-top d-flex align-items-center justify-content-center"
      ><i class="bi bi-arrow-up-short"></i
    ></a>



    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript"></script>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
  </body>
</html>

templates/Final_Preview_Pages/questionForSurvey.html
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
  integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous" />
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
  integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
<style>
  * {
    box-sizing: border-box;
  }

  body {
    background-color: #f1f1f1;
  }

  #regForm {
    background-color: #ffffff;
    margin: 100px auto;
    font-family: Raleway;
    padding: 40px;
    width: 80%;
    min-width: 300px;
  }

  h1 {
    text-align: center;
  }

  input {
    padding: 10px;
    width: 100%;
    font-size: 17px;
    font-family: Raleway;
    border: 1px solid #aaaaaa;
  }

  /* Mark input boxes that gets an error on validation: */
  input.invalid {
    background-color: #ffdddd;
  }

  /* Hide all steps by default: */
  .tab {
    display: none;
  }

  button {
    background-color: #04aa6d;
    color: #ffffff;
    border: none;
    padding: 10px 20px;
    font-size: 17px;
    font-family: Raleway;
    cursor: pointer;
  }

  button:hover {
    opacity: 0.8;
  }

  #prevBtn {
    background-color: #bbbbbb;
  }

  /* Make circles that indicate the steps of the form: */
  .step {
    height: 15px;
    width: 15px;
    margin: 0 2px;
    background-color: #bbbbbb;
    border: none;
    border-radius: 50%;
    display: inline-block;
    opacity: 0.5;
  }

  .step.active {
    opacity: 1;
  }

  /* Mark the steps that are finished and valid: */
  .step.finish {
    background-color: #04aa6d;
  }

  input[type="range"] {
    max-width: 90%;
    height: 10px;
    background: linear-gradient(to right, #f2f2f2, #f2f2f2);
    border: none;
    border-radius: 5px;
    outline: none;
    -webkit-appearance: none;
  }

  input[type="range"]::-webkit-slider-thumb {
    -webkit-appearance: none;
    appearance: none;
    width: 15px;
    height: 15px;
    border-radius: 50%;
    background-color: #04aa6d;
    cursor: pointer;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    transform: rotate(-30deg) translate(-50%, -50%);
  }

  input[type="range"]::-moz-range-thumb {
    width: 20px;
    height: 20px;
    border-radius: 50%;
    background-color: #04aa6d;
    cursor: pointer;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    transform: rotate(-45deg) translate(-50%, -50%);
  }

  input[type="range"]::-webkit-slider-runnable-track {
    height: 10px;
    border-radius: 5px;
    background: linear-gradient(to right, #04aa6d, #f2f2f2);
  }

  input[type="range"]::-moz-range-track {
    height: 10px;
    border-radius: 5px;
    background: linear-gradient(to right, #04aa6d, #f2f2f2);
  }
</style>

<body>
  <div class="container">
    Translate : 
    <select name="" id="">
      <option value=""></option> // from 
    </select>
  </div>
  <form id="regForm" method="POST">
    {% csrf_token %}

    <!-- One "tab" for each step in the form: -->

    <h1 style="color: #04aa6d" class="bold p-4">{{ survey }}</h1>

    <br />
    <br />

    {% if cat_list.length < 2 and cat_list.questions.length < 1  %}

    <h3 class="text-center text-danger">This Survey Has No Questions</h3>

    {% else %}

    <div id="questions-container">
      <hr class="mt-5" style="border: black solid 1px" />
      {% for i in cat_list %}
      <ul class="question-list" style="list-style: none">
        {% if i.questions %}
        <div class="tab">
          {% if i.category == 'No Category'  %}
          <h5 class="text-gray mb-5">
            <span class="ml-2" style="color: #04aa6d; font-weight: bold; font-size: 20px">
              Category </span>{{ i.category }}
          </h5>
          {% endif %}
          {% for question in i.questions %}
          <li style="
                border-left: 6px solid #04aa6d;
                border-radius: 8px;
                margin-left: 30px;
              "
              class="col-lg-8 col-md-10 col-sm-12">
            <div class="row" style="margin-left: 10px">
              <div class="col-11">
                <p style="padding-top: 40px; font-size: 14px">
                  {{ question.title }}
                </p>
              </div>
            </div>

            {% if question.label %}
            <div class="row" style="margin-left: 30px">
              <div class="col-1">
                <span style="color: #04aa6d; font-weight: bold; font-size: 14px">
                  Lable 
                </span>
              </div>
              <div class="col-11">
                <p style="font-size: 12px;color: #04aa6d;" class="ml-1">
                  {{ question.label }}
                </p>
              </div>
            </div>
            {% endif %} 
            {% if question.question_type == "rating" %}
            <div>
              <label style="margin: 20px; margin-left: 30px; font-weight: bold">
                Choose 0 - 10
              </label>
              <input type="range" id="progressInput{{question.id}}" min="0" max="10" value="0"
                oninput="updateProgressBar(this.value, {{question.id}})" style="margin: 20px; margin-left: 30px"
                name="answer_{{ question.id }}" />
              <span style="font-size: 20px; font-weight: bold; color: #04aa6d"
                id="progressLabel{{question.id}}">0</span>
            </div>
            {% elif question.question_type == "radio" or question.question_type == "checkbox" %}
            <div>
              {% for choice in question.choice.all %}
              <div style="margin-left: -700px">
                <input type="{{question.question_type}}" name="choice_{{question.id}}" id="{{choice.id}}" value="{{choice.name}}"
                  {% if choice.checked %}checked{% endif %} style="margin-right: -800px" />
                <label for="{{choice.id}}">{{ choice.name }}</label>
              </div>
              {% endfor %}
            </div>
            {% elif question.question_type == "number" %}
            <input style="margin-left: 50px" class="form-control" type="number" name="answer_{{ question.id }}"
              placeholder="Answer..." required />
            {% elif question.question_type == "email" %}
            <input style="margin-left: 50px" class="form-control" type="email" name="answer_{{ question.id }}"
              placeholder="Email..." required />
            {% elif question.question_type == "url" %}
            <input style="margin-left: 50px" class="form-control" type="url" name="answer_{{ question.id }}"
              placeholder="URL..." required />
            {% elif question.question_type == "date" %}
            <input style="margin-left: 50px" class="form-control" type="date" name="answer_{{ question.id }}"
              placeholder="Date..." required />
            {% elif question.question_type == "text" %}
            <input style="margin-left: 50px" class="form-control" type="text" name="answer_{{ question.id }}"
              placeholder="Answer..." required />
            {% else %}
            <textarea style="margin-left: 50px" class="form-control" name="answer_{{ question.id }}"
              placeholder="Enter your text here..." required></textarea>
            {% endif %} {% if question.allow_doc %}
            <input style="margin-left: 30px" class="form-control m-3 ml-4" type="file" name="file_{{ question.id }}"
              placeholder="File..." required />
            {% endif %} {% if question.doc_label %}
            <p style="margin: 20px">
              <label style="margin-left: 30px; font-weight: bold" class="ml-4 mt-3" for="file{{ question.id }}">Document
                label</label>
              {{ question.doc_label }}
            </p>
            {% endif %}

            <br />
          </li>
          <br />
          {% endfor %}
        </div>
        {% endif %}
      </ul>

      {% endfor %}
    </div>

    <div style="overflow: auto">
      <div style="float: right">
        <button type="button" id="prevBtn" onclick="nextPrev(-1)">
          Previous
        </button>
        <button type="button" id="nextBtn" onclick="nextPrev(1)">Next</button>
      </div>
    </div>
    <!-- Circles which indicate the steps of the form: -->

    <div style="text-align: center; margin-top: 40px">
      {% for i in cat_list %}
      <span class="step"></span>
      {% endfor %}
    </div>

    {% endif %}
  </form>

  <script>
    function updateProgressBar(value, questionId) {
      var progressInputId = "progressInput" + questionId;
      var progressLabelId = "progressLabel" + questionId;

      var progressBar = document.getElementById(progressInputId);
      var progressLabel = document.getElementById(progressLabelId);

      var progress = (progressBar.value / progressBar.max) * 100;
      progressBar.style.background = `linear-gradient(to right, #04AA6D ${progress}%, #f2f2f2 ${progress}%)`;

      progressLabel.textContent = progressBar.value;
    }
    var currentTab = 0; // Current tab is set to be the first tab (0)
    showTab(currentTab); // Display the current tab

    function showTab(n) {
      // This function will display the specified tab of the form...
      var x = document.getElementsByClassName("tab");
      x[n].style.display = "block";
      //... and fix the Previous/Next buttons:
      if (n == 0) {
        document.getElementById("prevBtn").style.display = "none";
      } else {
        document.getElementById("prevBtn").style.display = "inline";
      }
      if (n == x.length - 1) {
        document.getElementById("nextBtn").innerHTML = "Submit";
      } else {
        document.getElementById("nextBtn").innerHTML = "Next";
      }
      //... and run a function that will display the correct step indicator:
      fixStepIndicator(n);
    }

    function nextPrev(n) {
      // This function will figure out which tab to display
      var x = document.getElementsByClassName("tab");
      // Exit the function if any field in the current tab is invalid:
      if (n == 1 && !validateForm()) return false;
      // Hide the current tab:
      x[currentTab].style.display = "none";
      // Increase or decrease the current tab by 1:
      currentTab = currentTab + n;
      // if you have reached the end of the form...
      if (currentTab >= x.length) {
        // ... the form gets submitted:
        document.getElementById("regForm").submit();
        return false;
      }
      // Otherwise, display the correct tab:
      showTab(currentTab);
    }

    function validateForm() {
      // This function deals with validation of the form fields
      var x,
        y,
        i,
        valid = true;
      x = document.getElementsByClassName("tab");
      y = x[currentTab].getElementsByTagName("input");
      // A loop that checks every input field in the current tab:
      for (i = 0; i < y.length; i++) {
        // If a field is empty...
        if (y[i].value == "") {
          // add an "invalid" class to the field:
          y[i].className += " invalid";
          // and set the current valid status to false
          valid = false;
        }
      }
      // If the valid status is true, mark the step as finished and valid:
      if (valid) {
        document.getElementsByClassName("step")[currentTab].className +=
          " finish";
      }
      return valid; // return the valid status
    }

    function fixStepIndicator(n) {
      // This function removes the "active" class of all steps...
      var i,
        x = document.getElementsByClassName("step");
      for (i = 0; i < x.length; i++) {
        x[i].className = x[i].className.replace(" active", "");
      }
      //... and adds the "active" class on the current step:
      x[n].className += " active";
    }
  </script>
</body>

</html>

templates/Final_Preview_Pages/section_list_anunymous.html
{% load static %}
{% include "includes/head.html" %}
<!DOCTYPE html>
<html lang="en">

{% include "includes/greetingHead.html" %}
 
    <style>
      .ft p {
        font-size: x-small;
        font-weight: 400;
      }
      .card {
        box-shadow: 0 20px 27px 0 rgb(0 0 0 / 5%);
      }

      .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 0 solid rgba(0, 0, 0, 0.125);
        border-radius: 1rem;
      }

      .card-body {
        -webkit-box-flex: 1;
        -ms-flex: 1 1 auto;
        flex: 1 1 auto;
        padding: 1.5rem 1.5rem;
      }
      .avatar-text {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        align-items: center;
        background: #000;
        color: #fff;
        font-weight: 700;
      }

      .avatar {
        width: 3rem;
        height: 3rem;
      }
      .rounded-3 {
        border-radius: 0.5rem !important;
      }
      .mb-2 {
        margin-bottom: 0.5rem !important;
      }
      .me-4 {
        margin-right: 1.5rem !important;
      }
    </style>

  <body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top">
      <div
        class="container-fluid container-xl d-flex align-items-center justify-content-between"
      >
        <a href="#" class="logo d-flex align-items-center">
          <img src="{% static 'assets/img/logo.png' %}" alt="" />
          <span style="color: rgb(9, 109, 9)">MOPD</span>
        </a>

        {%load static %}

      
      </div>
    </header>
    <!-- End Header -->

    <!-- ======= Hero Section ======= -->
    <section id="hero" class="hero mt-3 align-items-center">
     
    <div class="container">
      <div class="text-center mb-5">
        <h3  style="font-size: 40px;color:rgb(9, 109, 9);font-weight: bold;">Section Lists</h3>
      </div>


    
      <div class="row">
    





        {% if sections %}
          
        {% for section in sections  %}
        {% if section in surveys_with_responses %}


        <div class="col-md-3 col-sm-6 col-lg-4 p-1" style="pointer-events: none; opacity: 0.5;">
          <a href="{% url 'survey_managment:questionForSurveyAnonymous' id=section.id user_response_id=user_response_id %}" style="color: black;text-decoration:none;">
          <div class="info-box shadow">
                  <span class="info-box-icon" style="color: rgb(9, 109, 9);">
                      <i class="far fa-copy"></i>
                  </span> 
                                
                  <div class="info-box-content p-3">
                      <span class="info-box-text">{{ section.name }}</span>
                      <span class="info-box-text">{{ section.instruction }}</span>
                      <span class="info-box-text">{{ section.question.count }} Questions </span>
                      
                  </div>
                  <span class="info-box-text text-danger">Done</span>    
              </div>
          </a>
      </div>
      

         
           
           {% else %}

           <div class="col-md-3 col-sm-6 col-lg-4 p-1">
            <a href="{% url 'survey_managment:questionForSurveyAnonymous' id=section.id user_response_id=user_response_id %}" style="color: black;text-decoration:none;">
            <div class="info-box shadow">
                <span class="info-box-icon" style="color: rgb(9, 109, 9);">
                  <i class="far fa-copy"></i>
                </span>                   
                <div class="info-box-content p-3">
                      <span class="info-box-text">{{ section.name }}</span>
                      <span class="info-box-text">{{ section.instruction }}</span>
                      <span class="info-box-text">{{ section.question.count }} Questions </span>
                  </div>
              </div>
          </a>
          </div>

           {% endif %}
            {% endfor %}

            {% else %}
            <div class="container-fluid" style="display: flex; align-items: center;">
              <p style="margin: auto; color: darkgray;">No section found. Your  news sections will occure here.</p>
            </div>

            {% endif %}
           </div>
    </section>
    <!-- End Hero -->
    <!-- ======= Services Section ======= -->

  
    <a
      href="#"
      class="back-to-top d-flex align-items-center justify-content-center"
      ><i class="bi bi-arrow-up-short"></i
    ></a>



    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript"></script>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
  </body>
</html>