survey_managment/urls.py
from django.urls import path
from .import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'survey_managment'


urlpatterns = [
    path('',views.indexView, name='Index'),
    path('surveyCreation/',views.surveyCreationView, name='SurveyCreation'),
    path('change_password/', views.change_password,name='change_password'),
    path('forgotPassword/', views.forgotPasswordView,name='forgotPassword'),
    # path('login/', views.loginView, name='login'),

    path('compareData/', views.compareDataView, name='compareData'),
    path('questionCreationByType/<int:section_id>/', views.questionCreationByType, name='questionCreationByType'),
     path('sections/<int:survey_id>/', views.sections, name='sections'),
    path('sectionCreation/<int:survey_id>/', views.sectionCreation, name='sectionCreation'),
    path('newQuestion/<str:questionType>/<int:s_id>/', views.newQuestion, name='newQuestion'),
    # path('newCategory/', views.newCategory, name='newCategory'),
    path('createQuestion/<int:survey_id>/', views.createQuestion, name='createQuestion'),
    path('save_category/' , views.save_category, name='save_category'),

    path('survey/', views.survey, name='survey'),
    path('inbox/', views.inbox, name='inbox'),
    path('inbox/<int:message_id>/reply/', views.reply_to_message, name='reply_to_message'),
    path('sent/', views.sent, name='sent'),
    path('draft/', views.draft, name='draft'),
    path('trash/', views.trash, name='trash'),
    path('compose/', views.compose, name='compose'),
    path('read/<int:id>', views.read, name='read'),
    
    path('chooseSurvey/<int:id>/<int:choose_id>/', views.chooseSurvey, name='chooseSurvey'),
    path('displayQuestion/<int:id>/', views.displayQuestion, name='displayQuestion'),
    path('catagorizedQuestion/<int:id>/', views.catagorizedQuestion, name='catagorizedQuestion'),
    path('choose-target/<int:survey_id>/<int:question_id>/', views.chooseTarget, name='chooseTarget'),
    path('questionCreationByType/<int:survey_id>/', views.questionCreationByType, name='questionCreationByType'),
    path('QuestionCategories/', views.QuestionCategories, name='QuestionCategories'),
    path('survey/', views.survey, name='survey'),
    path('line_ministrys/', views.line_ministrys, name='line_ministrys'),
    path('line_ministrys/<int:id>', views.line_ministry_detail, name='line_ministry_detail'),
    path("pending_response/",views.pending_response,name ='pending_response'),
    path('survey_detail/<int:id>/<int:assesment_id>', views.survey_detail, name='survey_detail'),
    path('user_response_list/<int:id>', views.user_response_list, name='user_response_list'),
    path('user_response/<int:id>/<int:response_id>', views.user_response, name='user_response'),
    # path('chooseSurvey/<int:id>/<int:choose_id>/', views.chooseSurvey, name='chooseSurvey'),
    path('displayQuestion/<int:survey_id>/', views.displayQuestion, name='displayQuestion'),
    path('jsonSender/' , views.jsonSender , name = 'jsonSender'),
    # path('choose-target/<int:survey_id>/<int:question_id>/', views.chooseTarget, name='chooseTarget'),
    path('get_json/',views.get_data,name='get_data'),
    path('filter_data/',views.filter,name='filter'),
    path('years/',views.YearDataview,name="years"),
    path('years2/',views.YearDataview2,name="years2"),
    # path('choose-target/<int:survey_id>/<int:question_id>/', views.chooseTarget, name='chooseTarget'),   
    path('greetingpage/',views.greetingpage_view, name='greetingpage'),
    path('surveylists/',views.survey_listss_views, name='surveylists'),
    path('section_list/<int:survey_id>/',views.section_list, name='section_list'),
    path('section_list_anonymous/<int:survey_id>/<int:user_response_id>',views.section_list_anonymous, name='section_list_anonymous'),
    path('user_info/',views.user_info, name='user_info'),
    path('surveylistsAnonymous/<int:user_response_id>',views.anonymous_survey_listss_views, name='anonymous_survey_listss_views'),
    path('questionForSurvey/<int:id>/<int:assesment_id>' , views.questionForSurvey , name = 'questionForSurvey'),
    path('questionForSurveyAnonymous/<int:id>/<int:user_response_id>' , views.questionForSurveyAnonymous , name = 'questionForSurveyAnonymous'),
    path('recomended_survey_list/<int:survey_id>' , views.recomended_survey_list , name = 'recomended_survey_list'),
    path('recomended_survey/<int:id>' , views.recomended_survey , name = 'recomended_survey'),
    path('previous_analysis/' , views.previous_analysis , name = 'previous_analysis'),
    path("load_survey/",views.load_survey,name ='load_survey'),
    path("load_ministry/",views.load_ministry,name ='load_ministry'),
    path("assessment_category/", views.AssesmentCatagory, name='assessment_category'),
    path("LineMinistryFilter/", views.LineMinistryFilter, name='LineMinistryFilter'),




]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/category.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

{% include "includes/head.html" %}


<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">
    {% include 'includes/topNavbar.html' %}
    {% include 'includes/sideNavbar.html' %}

    <div class="content-wrapper" style="background-color: white;">
  
      <div class="container">
        
        <h4 class="mt-3"> Categories </h4>

        <div class="container">
            <div class="row mt-3">

                <div class="col-lg-8">
                    <table class="table table-striped table-hover success">
                        <thead>
                        <tr>
                            <th> C_ID </th>
                            <th> P_ID </th>
                            <th> Name </th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for i in categories %}
                                <tr>
                                    <td> {{ i.id }} </td>
                                    {% if  i.parent.id %} 
                                        <td> {{ i.parent.id }}  </td>
                                    {% else %}
                                        <td> - </td>
                                    {% endif %}
                                    <td> {{ i.name}} </td>
                                    
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            <div class="col-lg-4">
                <h6 class="m-3 text-center"> Add New Category </h6>
                <form action="" method="post">
                    {% csrf_token %}
                    <label for=""> Name </label>
                    <input type="text" class="form-control" name="zcategory" id="">

                    <label for=""> Parent Category</label>
                    <select id="" name="parent" class="form-select" >
                        <option value="">Select Type</option>
                        {% for j in categories %}
                            <option value="{{j}}"> {{j}} </option>
                        {% endfor %}
                    </select>

                    <button type="submit" class="btn m-3 " style="border:2px solid #4c956c;"> CREATE </button>
                </form>
            </div>
            
           
            </div>
        </div>
      </div>

    </div>
  </div>
  

  {% include "includes/scripts.html" %}
  <!-- <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script>
  <script>
      $(document).ready( function () {
      $('#myTable').DataTable();
  } );
  </script> -->


</body>
</html>

templates/line_ministry_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

{% include "includes/head.html" %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css" />
<style>
  .topLinks {
    display: flex;
    justify-content: center;
  }

  .topLinks li {
    margin: 10px;
    border-radius: 10px;
    border-bottom: 3px solid rgba(178, 223, 219, 1.0);
  }

  .topLinks li:hover {
    background-color: rgba(178, 223, 219, 1.0);
  }

  .topLinks li .nav-link.active {
    background-color: #46b583;
  }

  .card {
    background-color: transparent !important;
    border: none !important;
    box-shadow: none !important;
    /* Add any additional styles as needed */
  }

</style> ,

<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">
    {% include 'includes/topNavbar.html' %} {% include 'includes/sideNavbar.html' %}

    <div class="content-wrapper" style="background-color: white;">


      <div class="container">

        {% if minister %}

        <div class="row">

          <div class="col-lg-12">
            <div class="card ">
              <div class="card-header p-2">
                <ul class="nav nav-pills topLinks">
                  <li class="nav-item">
                   
                    <a class="nav-link active" href="#QuestionList" data-toggle="tab">Question List</a>
                  </li>
                  <li class="nav-item">
                  
                    <a class="nav-link" href="#timeline" data-toggle="tab">User Response</a>
                  </li>
                </ul>
              </div>


              <div class="card-body">
                <div class="tab-content">

                  <div class="active tab-pane" id="QuestionList">
                    <h4 class="text-center text-info mt-3">
                      Surveys Assigned to  {{ line_ministry.name }}
                     </h4>
                 {% if survey %}
                 <div class="row mt-3" id="questions-container">
                  {% for i in survey %}
                      
                  <div class="col-md-3 col-sm-6 col-lg-4 hidden-transition">
                   <a href="{% url 'survey_managment:survey_detail' id=i.id %}" style="color: black; text-decoration: none;">
                      <div class="info-box shadow">
                        <span class="info-box-icon" style="color: #0096c7;">
                          <i class="far fa-copy"></i>
                        </span>                   
                        <div class="info-box-content">
                              <span class="info-box-text">{{ i.name }}</span>
                        </div>
                      </div>
                  </a>
                  </div>
                  
                  {% endfor %}
                </div>
      
                 {% else %}   

                 <p style="font-size: 1.2rem;">No Questions found For this survey.</p>
                 
                 {% endif %}

                  
                </div>

                  <div class="tab-pane" id="timeline">
                    <div class="container card shadow mt-2">
                      <h4 class="text-center text-info mb-3">
                        Responses by {{ line_ministry.name }}
                    </h4>
                      {% if user_responses %}
                        <table class="table table-striped table-hover success">
                          <thead>
                            <tr>
                              <th>Survey </th>
                              <th>Submited At </th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for response in user_responses %}
                              <tr>
                                <td><a style="text-decoration: none; color: black;" href="{% url 'survey_managment:user_response' id=response.forsection.id response_id=response.id %}">{{ response.forsection }}</a></td>
                                <td>{{ response.submitted_at }}</td>
                              </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      {% else %}
                        <p class="text-center text-danger" style="font-size: 1.2rem;">No responses found.</p>
                      {% endif %}
                    </div>
                  </div>

                </div>
              </div>
            </div>

          </div>
        </div>

        {% else %}

           <h2 class="text-center text-danger mt-5"> No User for this ministry </h2>

        {% endif %}

      </div>
    </div>
  </div>
  

  <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script>
  <script>
      $(document).ready( function () {
      $('#myTable').DataTable();
  } );
  </script>

    <script>
      $(document).ready(function () {
        // Search functionality
        $('#search-input').on('keyup', function () {
          var value = $(this).val().toLowerCase();
          $('.question-row').filter(function () {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
          });
        });
    
        // Select all functionality
        $('#select-all-btn').on('click', function () {
          $('.question-checkbox').prop('checked', true);
        });
      });
    </script>
</body>
</html>

templates/pendingResponse.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  

{% include "includes/head.html" %}


<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">
    {% include 'includes/sideNavbar.html' %}
    {% include 'includes/topNavbar.html' %}
    {% include 'includes/message.html' %}

    <div class="content-wrapper" style="background-color: white;">
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active">Pending Responses.</li>
              </ol>
            </div>
          </div>
        </div>
      </div>


      <section class="container-fluid" >

        <div class="container card shadow mt-2">
          <h1 class="text-center text-info m-3"> Pending Responses </h1>
                       
          {% if user_responses %}
            <table class="table table-striped table-hover table-responsive success">
              <thead>
                <tr>
                  <th>Response by</th>
                  <th>Submitted at</th>
                  <th>Line ministry </th>
                  <th>For section </th>
                  <th>Statues </th>
                </tr>
              </thead>
              <tbody>
                {% for response in user_responses %}
                  <tr>
                    <td><a style="text-decoration: none; color: black;" href="{% url 'survey_managment:user_response' id=response.forsection.v response_id=response.id %}">{{ response.submitted_by }}</a></td>
                    <td>{{ response.submitted_at }}</td>
                    <td>{{ response.submitted_by.Line_ministry }}</td>
                    <td>{{ response.forsection }}</td>
                    <td>{{ response.status }}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% else %}
            <p style="font-size: 1.2rem;">No responses found.</p>
          {% endif %}
        </div>
  

      </section>
    </div>
  </div>

  {% include "includes/scripts.html" %}
  

  <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script>
  <script>
      $(document).ready( function () {
      $('#myTable').DataTable();
  } );
  </script>

    <script>
      $(document).ready(function () {
        // Search functionality
        $('#search-input').on('keyup', function () {
          var value = $(this).val().toLowerCase();
          $('.question-row').filter(function () {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
          });
        });
    
        // Select all functionality
        $('#select-all-btn').on('click', function () {
          $('.question-checkbox').prop('checked', true);
        });
      });
    </script>
</body>
</html>

templates/survey_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

{% include "includes/head.html" %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css" />
<style>
  .topLinks {
    display: flex;
    justify-content: center;
  }

  .topLinks li {
    margin: 10px;
    border-radius: 10px;
    border-bottom: 3px solid rgba(178, 223, 219, 1.0);
  }

  .topLinks li:hover {
    background-color: rgba(178, 223, 219, 1.0);
  }

  .topLinks li .nav-link.active {
    background-color: #46b583;
  }

  .card {
    background-color: transparent !important;
    border: none !important;
    box-shadow: none !important;
    /* Add any additional styles as needed */
  }
  input[type="range"] {
    max-width: 90%;
    height: 10px;
    background: linear-gradient(to right, #f2f2f2, #f2f2f2);
    border: none;
    border-radius: 5px;
    outline: none;
    -webkit-appearance: none;
  }

  input[type="range"]::-webkit-slider-thumb {
    -webkit-appearance: none;
    appearance: none;
    width: 15px;
    height: 15px;
    border-radius: 50%;
    background-color: #04aa6d;
    cursor: pointer;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    transform: rotate(-30deg) translate(-50%, -50%);
  }

  input[type="range"]::-moz-range-thumb {
    width: 20px;
    height: 20px;
    border-radius: 50%;
    background-color: #04aa6d;
    cursor: pointer;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    transform: rotate(-45deg) translate(-50%, -50%);
  }

  input[type="range"]::-webkit-slider-runnable-track {
    height: 10px;
    border-radius: 5px;
    background: linear-gradient(to right, #04aa6d, #f2f2f2);
  }

  input[type="range"]::-moz-range-track {
    height: 10px;
    border-radius: 5px;
    background: linear-gradient(to right, #04aa6d, #f2f2f2);
  }

</style>

<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">

    {% include 'includes/topNavbar.html' %} {% include 'includes/sideNavbar.html' %}

    <div class="content-wrapper" style="background-color: white;">


      <div class="container">
        <div class="row">

          <div class="col-lg-12">
            <div class="card ">
              <div class="card-header p-2">
                <ul class="nav nav-pills topLinks">
                  <li class="nav-item">
                  
                    <a class="nav-link active" href="#QuestionList" data-toggle="tab">Question List</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#timeline" data-toggle="tab">User Response</a>
                  </li>
                </ul>
              </div>


              <div class="card-body">
                <div class="tab-content">

                  <div class="active tab-pane" id="QuestionList">
                    <h4 class="text-center text-info mt-3">
                      Questions for survey {{ survey.name }}
                     </h4>
                 {% if cat_list %}
                 
                 {% for i in cat_list %}

                 <ul class="question-list " style="list-style: none;margin-left:-23px">
                     {% if i.questions %}
                     <div class="tab">
                         <h5 class="text-gray mb-5">
                             {% if i.catagory.parent %}
                            {{ i.category.parent}}
                             {% endif %}
                             <span  style="color: #04aa6d; font-weight: bold ; font-size: 20px">
                              Category
                          </span>{{ i.category }}</h5>
                         {% for question in i.questions %}
               
                         <li style="border-left: 6px solid #04aa6d; border-radius: 8px; margin-left: 20px;">
                             <div class="row" style="margin-left:10px">
                                 <div class="col-11">
                                     <p style="padding-top:40px;font-size:18px;">{{ question.title }}</p>
                                 </div>
                             </div>
               
                             {% if question.label %}
                             <div class="row" style="margin-left:30px">
                                 <div class="col-1">
                                     <span  style="color: #04aa6d; font-weight: bold;font-size:16px">
                                         Description:
                                     </span>
                                 </div>
                                 <div class="col-11">
                                     <p style="font-size:16px" class="ml-5">{{ question.label }}</p>
                                 </div>
                             </div>
                             {% endif %}
               
                             {% if question.question_type == "rating" %}
                             <div>
                               <label style="margin:20px;margin-left:30px;font-weight:bold"> Choose 0 - 10 </label>
                               <input disabled type="range" id="progressInput{{question.id}}" min="0" max="10" value="0" oninput="updateProgressBar(this.value, {{question.id}})" style="margin:20px;margin-left:30px;" name="answer_{{ question.id }}">
                               <span style="font-size:20px;font-weight:bold;color:#04AA6D;" id="progressLabel{{question.id}}">0</span>
                             </div>
                           {% elif question.question_type == "radio" or question.question_type == "checkbox" %}
                           <div>
                            
                             {% for choice in question.choice.all %}
                            
                             <div style="margin-left:70px">
                               <input disabled type="{{question.question_type}}" name="{{choice.id}}" id="{{choice.id}}" value="{{choice.id}}" />
                               <label for="{{choice.id}}">{{ choice.name }}</label>
                             </div>
                             {% endfor %}
                           </div>
                           {% elif question.question_type == "number" %}
                             <input disabled style="margin-left:50px" class="form-control" type="number" name="answer_{{ question.id }}" placeholder="Answer..." required />
                           {% elif question.question_type == "email" %}
                             <input disabled style="margin-left:50px" class="form-control" type="email" name="answer_{{ question.id }}" placeholder="Email..." required />
                           {% elif question.question_type == "url" %}
                             <input disabled style="margin-left:50px" class="form-control" type="url" name="answer_{{ question.id }}" placeholder="URL..." required />
                           {% elif question.question_type == "date" %}
                             <input disabled style="margin-left:50px" class="form-control" type="date" name="answer_{{ question.id }}" placeholder="Date..." required />
                           {% elif question.question_type == "text" %}
                           <input disabled style="margin-left:50px" class="form-control" type="text" name="answer_{{ question.id }}" placeholder="Answer..." required />
                             {% else %}
                           <textarea disabled  style="margin-left:50px" class="form-control" name="answer_{{ question.id }}" placeholder="Enter your text here..." required></textarea>
                           {% endif %}
               
                             {% if question.allow_doc %}
                             <input disabled style="margin-left:30px" class="form-control m-3 ml-4" type="file" name="file_{{ question.id }}"
                                 placeholder="File..." required />
                             {% endif %}
                             {% if question.doc_label %}
                             <p style="margin:20px">
                                 <label style="margin-left:30px;font-weight:bold" class="ml-4 mt-3" for="file{{ question.id }}">Document
                                     label</label>
                                 {{ question.doc_label }}
                             </p>
                             {% endif %}
               
                             <br />
                         </li>
                         <br />
                         {% endfor %}
                     </div>
                     {% endif %}
                 </ul>
               
                 {% endfor %}

                 {% else %}  

                 <p style="font-size: 1.2rem;">No Questions found For this survey.</p>
                 
                 {% endif %}


                {% if user_responses  %}
                   
                {% else %}  
                   <a class="btn btn-primary" href="{% url 'survey_managment:questionCreationByType' survey_id %}">Add Questions</a>
                {% endif %}
                  </div>

                  <div class="tab-pane" id="timeline">
                    <div class="container card shadow mt-2">
                      <h4 class="text-center text-info mb-3">
                        Responses for survey {{ survey.name }}
                    </h4>
                      {% if user_responses %}
                        <table class="table table-striped table-hover success">
                          <thead>
                            <tr>
                              <th>Response by</th>
                              <th>Submitted at</th>
                              <th>Statues </th>
                            </tr>
                          </thead>
                          <tbody>
                            {% for response in user_responses %}
                              <tr>
                                <td><a style="text-decoration: none; color: black;" href="{% url 'survey_managment:user_response' id=survey_id response_id=response.id %}">{{ response.submitted_by }}</a></td>
                                <td>{{ response.submitted_at }}</td>
                                {% if response.status == "pending" %}
                                <td> <span class="info-box-text text-info">   <i class="nav-icon fas fa-spinner"></i> Pending </span> </td>
                                {% elif response.status == "approved" %}
                                <td> <span class="info-box-text text-info">    <i class="nav-icon fas fa-check"></i> Approved </span> </td>
                                {% else %}
                                <td> <span class="info-box-text text-info">    <i class="nav-icon fas fa-spinner"></i> Recomended </span> </td>
                                {% endif %}

                        
                              </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      {% else %}
                        <p class="text-center text-danger" style="font-size: 1.2rem;">No responses found.</p>
                      {% endif %}
                    </div>
                  </div>

                 

                 

                </div>
              </div>
            </div>

          </div>
        </div>

      </div>
      
    </div>
  </div>
  

  <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script>
  <script>
      $(document).ready( function () {
      $('#myTable').DataTable();
  } );
  </script>

    <script>
      $(document).ready(function () {
        // Search functionality
        $('#search-input').on('keyup', function () {
          var value = $(this).val().toLowerCase();
          $('.question-row').filter(function () {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
          });
        });
    
        // Select all functionality
        $('#select-all-btn').on('click', function () {
          $('.question-checkbox').prop('checked', true);
        });
      });
    </script>
</body>
</html>

templates/year2.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
{% include 'includes/head.html' %}

<body>
    <div class="wrapper">

        {% include 'includes/topNavbar.html' %}
        {% include 'includes/sideNavbar.html' %}

        <div class="content-wrapper">
            {% include "includes/dashbordNav.html" %}
            <section class="content">
                <div class="container-fluid">
                    <h4 style="text-align: center; color: #7ae582;" class="mt-3 mb-4">Assessment By Year</h4>
                    {% for i in survey_years %}
                    <div class="col-md-3 col-sm-6 col-12 p-1 hidden-transition">
                      <a href="{% url 'survey_managment:LineMinistryFilter' %}?year={{ i.created_at__year }}" style="color: black; text-decoration: none;">
                        <div class="info-box shadow">
                          <span class="info-box-icon" style="color: #0096c7;">
                            <i class="fa-solid fa-database"></i>
                          </span>                   
                          <div class="info-box-content">
                            <span class="info-box-text">
                              {{ i.created_at__year }}
                            </span>
                          </div>
                        </div>
                      </a>
                    </div>
                  {% endfor %}
                    
                </div>
            </section>
        </div>
    </div>


    {% include 'includes/scripts.html' %}
</body>

</html>